### ISSUE TITLE
Async Commands don't work properly

### ISSUE THREAD

**Issue by gnunua** [RobotlegsJS/RobotlegsJS-Macrobot#88]
**Describe the bug**

**To Reproduce**
1. Set up basic AsyncCommand ( Dealy Command) 
2. Add is to Sequence Macro Command 
3. Make  Sequence Macro Command  execute signal triggering
4. See an error on console

**Desktop (please complete the following information):**
 - OS: macOS Mojave v. 10.14.3
 - Browser: Chrome 
 - Version 72.0.3626.119

Here is the example code you can run:

```

@injectable()
export class DelayCommand extends AsyncCommand {
    public execute(): void {
        setTimeout(this.onTimeout.bind(this), 500);
    }

    protected onTimeout(): void {
        this.dispatchComplete(true);
    }
}


@injectable()
export class MyMacro extends SequenceMacro {
    public prepare():void {
        this.add(DelayCommand)
    }

    protected onComplete(success): void {
        console.log("All commands have been executed!");
    }
}

```

**Comment by gnunua** [comment]
@tiagoschenkel  Please ignore this issue. 
My robotlegs packages were not up to date.  That was the cause of the issue.

**Comment by tiagoschenkel** [comment]
@gnunua, no worries, so I'm closing the issue.
